project_id = "jaouwhckqqnaxqyfvgyq"

[functions.create-next-appointment]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.enrich-old-transactions]
verify_jwt = true

[functions.extract-quote-data]
verify_jwt = false

[functions.chatwoot-sync]
verify_jwt = true

[functions.chatwoot-webhook]
verify_jwt = false

[functions.analyze-receipt]
verify_jwt = false

[functions.analyze-policy]
verify_jwt = false

[functions.ocr-bulk-analyze]
verify_jwt = false
